### ISSUE TITLE
Trying to get property 'token' of non-object in file /vendor/ayles-software/xero-laravel/src/XeroHandler.php on line 11

### ISSUE THREAD

**Issue by code-crafter365** [ayles-software/xero-laravel#3]
Is there any tutorial or official documentation for this library? I have implemented the controller following as:
But I am not sure whether it's correct or not.
```
class XeroController extends Controller
{
    public function __invoke(XeroOAuth $xeroOAuth)
    {
        return $xeroOAuth->flow();
    }

    public function create()
    {
        $contacts = Xero::contacts()->get();
        return response()->json($contacts);
    }
}
```

**Comment by parkourben99** [comment]
This library is just a wrapper for laravel and helper for the oAuth flow. Look at the original library https://github.com/calcinai/xero-php
